[workspace]
resolver = "2"
members = [
  "crates/sc-anim",
  "crates/sc-input",
  "crates/sc-config",
  "crates/sc-keys",
  "crates/sc-shell-model",
  "crates/sc-catalog",
  "crates/sc-layout",
  "crates/sc-icons",
  "crates/sc-search",
  "crates/sc-compositor",
]

[workspace.package]
edition = "2021"
license = "GPL-2.0-only"

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.debugging]
inherits = "dev"
debug = true


[profile.release]
lto = "thin"
codegen-units = 1
