[workspace]
resolver = "2"
members = [
  "crates/sc-anim",
  "crates/sc-input",
  "crates/sc-shell-model",
  "crates/sc-config",
  "crates/sc-layout",
  "crates/sc-icons",
  "crates/sc-compositor",
]

[workspace.package]
edition = "2021"
license = "MIT"

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1
