[package]
name = "sc-search"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "sc-search"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.29", default-features = false, features = ["glow", "wayland"] }
egui = "0.29"
sc-config = { path = "../sc-config" }
sc-shell-model = { path = "../sc-shell-model" }
sc-icons = { path = "../sc-icons" }
